apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-rgds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/josuecodjo/platform.git
    targetRevision: HEAD
    path: rgds
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kro
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
